title: TPEN Prompts

collections:
  pages:
    output: true
    permalink: /:path/
  tools:
    output: true
    permalink: /tools/:name
  scripts:
    output: true
    permalink: /scripts/:name/

defaults:
  - scope:
      path: ""
      type: tools
    values:
      layout: null
      sitemap: false
